# Generated by Django 4.2.15 on 2024-08-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(blank=True, max_length=50, null=True)),
                ('stu_dob', models.DateField()),
                ('stu_course', models.CharField(max_length=30, null=True)),
                ('address_city', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'CollegeModel',
                'verbose_name_plural': 'CollegeModels',
            },
        ),
    ]
